---
application:
  name: "afilechooser"
  project: "teabot"
  organization: "QoveryCommunity"
routers:
- name: "main-afilechooser"
  routes:
  - application_name: "afilechooser"
    paths:
    - "/*"
